on:
  push:
    branches: [ "main" ]

jobs:
  VM_SetUpJDK:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
      #use the repository
    - name: Set up JDK 17
      uses: actions/setup-java@v3 
        #installiert die Java Version
      with:
        java-version: '17'
        distribution: 'temurin' 
          #Temurin-Distribution von Eclipse Adoptium verwendet - wird von setUp JDK unterstützt
        cache: maven 
          #In diesem Workflow wird der Maven-Abhängigkeitscache zwischen den Builds wiederhergestellt, um die Build-Zeit zu verkürzen
    - name: Build with Maven
      run: mvn -B package --file pom.xml
